--------------------------------------------------------
--  Fichier créé - samedi-janvier-02-2021   
--------------------------------------------------------
DROP TABLE "CARTE" cascade constraints;
DROP TABLE "CLINET" cascade constraints;
DROP TABLE "CONTRAT" cascade constraints;
DROP TABLE "EMPLOYEE" cascade constraints;
DROP TABLE "LIVRAISON" cascade constraints;
DROP TABLE "PRODUIT" cascade constraints;
DROP TABLE "PROMOTION" cascade constraints;
DROP TABLE "PUBLICITE" cascade constraints;
--------------------------------------------------------
--  DDL for Table CARTE
--------------------------------------------------------

  CREATE TABLE "CARTE" 
   (	"REF" VARCHAR2(20 BYTE), 
	"CINCLIENT" VARCHAR2(20 BYTE), 
	"NOMBREDESPOINTS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLINET
--------------------------------------------------------

  CREATE TABLE "CLINET" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"CIN" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTRAT
--------------------------------------------------------

  CREATE TABLE "CONTRAT" 
   (	"SALAIRE" VARCHAR2(20 BYTE), 
	"DUREE" VARCHAR2(20 BYTE), 
	"DATEDEB" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"CIN" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "EMPLOYEE" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"POSTE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVRAISON
--------------------------------------------------------

  CREATE TABLE "LIVRAISON" 
   (	"ADDD" VARCHAR2(20 BYTE), 
	"CIN" VARCHAR2(20 BYTE), 
	"NAME1" VARCHAR2(20 BYTE), 
	"REF" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "PRODUIT" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PAYS" VARCHAR2(20 BYTE), 
	"QT" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROMOTION
--------------------------------------------------------

  CREATE TABLE "PROMOTION" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"POURCENTAGE" VARCHAR2(20 BYTE), 
	"DATEE" VARCHAR2(20 BYTE), 
	"ID_P" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PUBLICITE
--------------------------------------------------------

  CREATE TABLE "PUBLICITE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"DUREE" VARCHAR2(20 BYTE), 
	"ID_P" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CARTE
SET DEFINE OFF;
REM INSERTING into CLINET
SET DEFINE OFF;
REM INSERTING into CONTRAT
SET DEFINE OFF;
Insert into CONTRAT (SALAIRE,DUREE,DATEDEB,EMAIL,CIN) values ('950','6','05/02/2020','fleenfouleni@gmail.com','12345678');
Insert into CONTRAT (SALAIRE,DUREE,DATEDEB,EMAIL,CIN) values ('950','6','05/02/2020','ahmedmabrouk@gmail.com','12345687');
Insert into CONTRAT (SALAIRE,DUREE,DATEDEB,EMAIL,CIN) values ('950','6','05/02/2020','aminamejri@gmail.com','12345867');
Insert into CONTRAT (SALAIRE,DUREE,DATEDEB,EMAIL,CIN) values ('700','3','05/02/2020','fathighanoouchi@gmail.com','12348567');
Insert into CONTRAT (SALAIRE,DUREE,DATEDEB,EMAIL,CIN) values ('700','3','05112/2020','mahjoubmrad@gmail.com','70206050');
Insert into CONTRAT (SALAIRE,DUREE,DATEDEB,EMAIL,CIN) values ('700','3','07/11/2020','azizmahdi@gmail.com','95353932');
Insert into CONTRAT (SALAIRE,DUREE,DATEDEB,EMAIL,CIN) values ('1050','36','01/11/2020','azizhosni@gmail.com','26425469');
Insert into CONTRAT (SALAIRE,DUREE,DATEDEB,EMAIL,CIN) values ('5000','48','22/02/2020','mohamedaziz.mazigh@esprit.tn','22620837');
Insert into CONTRAT (SALAIRE,DUREE,DATEDEB,EMAIL,CIN) values ('10000','6','01/02/','fardfard@gmail.com','20202020');
REM INSERTING into EMPLOYEE
SET DEFINE OFF;
Insert into EMPLOYEE (CIN,PRENOM,AGE,NOM,POSTE) values ('12345678','fleen','20','fouleni','employee');
Insert into EMPLOYEE (CIN,PRENOM,AGE,NOM,POSTE) values ('12345687','ahmed','22','mabrouk','employee');
Insert into EMPLOYEE (CIN,PRENOM,AGE,NOM,POSTE) values ('12345867','amina','25','mejri','employee');
Insert into EMPLOYEE (CIN,PRENOM,AGE,NOM,POSTE) values ('12348567','fathi','50','ghanoouchi','chauffeur ');
Insert into EMPLOYEE (CIN,PRENOM,AGE,NOM,POSTE) values ('22620837','aziz','20','mazigh','directeur ');
Insert into EMPLOYEE (CIN,PRENOM,AGE,NOM,POSTE) values ('95353932','aziz','20','mahdi','jardinier');
Insert into EMPLOYEE (CIN,PRENOM,AGE,NOM,POSTE) values ('26425469','aziz','20','hosni','responsable ');
Insert into EMPLOYEE (CIN,PRENOM,AGE,NOM,POSTE) values ('70206050','mrad','35','mahjoub','chauffeur ');
Insert into EMPLOYEE (CIN,PRENOM,AGE,NOM,POSTE) values ('2020202','ahmed','25','ahmed','directeur');
REM INSERTING into LIVRAISON
SET DEFINE OFF;
REM INSERTING into PRODUIT
SET DEFINE OFF;
REM INSERTING into PROMOTION
SET DEFINE OFF;
REM INSERTING into PUBLICITE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CONTRAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTRAT_PK" ON "CONTRAT" ("EMAIL", "CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLOYEE_PK" ON "EMPLOYEE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CONTRAT
--------------------------------------------------------

  ALTER TABLE "CONTRAT" ADD CONSTRAINT "CONTRAT_PK" PRIMARY KEY ("EMAIL", "CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CONTRAT" MODIFY ("CIN" NOT NULL ENABLE);
 
  ALTER TABLE "CONTRAT" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "EMPLOYEE" MODIFY ("CIN" NOT NULL ENABLE);
